// Generated by CoffeeScript 1.10.0
var announce, request;

request = require('request');

announce = function(arg) {
  var active, api_key;
  api_key = arg.api_key, active = arg.active;
  return function(event) {
    if (active !== false) {
      return request.post({
        url: 'http://webhooks.nexus.prontotype.us/events',
        json: event,
        headers: {
          'api-key': api_key
        }
      });
    }
  };
};

module.exports = announce;
