// Generated by CoffeeScript 1.10.0
var announce, isStatic;

announce = require('nexus-announce');

isStatic = function(path) {
  return path.match(/\.\w+$/);
};

module.exports = function(config) {
  return function(project_name) {
    return function(req, res, next) {
      var ref;
      if (req.method.toLowerCase() === 'get' && !isStatic(req.path)) {
        announce(config)({
          type: 'page-view',
          project: project_name,
          data: {
            page: req.path.slice(1) || 'home',
            ip: req.headers['x-forwarded-for'] || req.connection.remoteAddress,
            ua: req.get('User-Agent'),
            session_id: (ref = req.session) != null ? ref.id : void 0,
            user: res.locals.user
          }
        });
      }
      return next();
    };
  };
};
